services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: travel_planner_web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: unless-stopped
